apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: xfusion
spec:
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron-xfusion
            image: nginx:latest
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Welcome to xfusioncorp.
          restartPolicy: OnFailure
