apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tomcat-namespace-datacenter
  name: tomcat-deployment-datacenter
  labels:
    app: tomcat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat-container-datacenter
        image: gcr.io/kodekloud/centos-ssh-enabled:tomcat
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  namespace: tomcat-namespace-datacenter
  name: tomcat-service-datacenter
spec:
  selector:
    app: tomcat
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32227
  type: NodePort
